### PR TITLE
avs-device-sdk: add recipe

### PR DESCRIPTION
**Pull request by sashko**
Added recipes for Alexa Voice Service (AVS) Software Development Kit.

Recipes were taken from https://github.com/alexa/avs-device-sdk and
adapted to PELUX.

Signed-off-by: Oleksandr Kravchuk <oleksandr.kravchuk@pelagicore.com>

### CODE REVIEW

**Comment by JEderonn** [comment]
I think we should use Alexa Auto SDK, not device SDK.

**Comment by sashko** [comment]
> Alexa Auto SDK

Alexa Auto SDK is just a module for Alexa SDK.

**Comment by JEderonn** [comment]
> Alexa Auto is just set of modules for Alexa SDK.
Ok, great, I didn't know, thought there were two variants of SDK.

**Comment by martin-ejdestig** [comment]
Question: Is there some way we could use what is in the SDK directly without copying it? Or is that too hard/harder? Would be nice to not maintain copies, I am  guessing.

**Comment by martin-ejdestig** [comment]
> Could you please rephrase your question? I am not sure I understand it correctly.

Use the recipes that are in the repository. You mentioned in #266 that the recipes only are for rocko. But I have no idea if you have tried to use them without copying since you just say "adapted to PELUX".

**Comment by sashko** [comment]
> > Could you please rephrase your question? I am not sure I understand it correctly.
> 
> Use the recipes that are in the repository directly. You mentioned in #266 that the recipes only are for rocko. But I have no idea if you have tried to use them without copying since you just say "adapted to PELUX" without explaining why and what adaptations were necessary.

I cannot use the layer since Yocto since `sumo` requires `LAYERSERIES_COMPAT` to be set, and Amazon doesn't accept any PRs.

Also, it is not updated for a quite while, so we may end up bumping package version ourselves in the future. We need one recipe from the entire layer anyway.

**Comment by erikboto** [comment]
Shouldn't recipes like this live in meta-bistro? According to the old thoughts, and the README of meta-pelux, this is the main idea behind meta-pelux and meta-bistro:

`The relationship with meta-bistro, which is also developed at Pelagicore, is that meta-bistro contains general software recipes and configurations, aimed at the IVI domain, but no distribution and no images, whereas meta-pelux builds on top of meta-bistro by adding a distro and recipes to build complete system images.`

**Comment by sashko** [comment]
> Shouldn't recipes like this live in meta-bistro? According to the old thoughts, and the README of meta-pelux, this is the main idea behind meta-pelux and meta-bistro:
> 
> `The relationship with meta-bistro, which is also developed at Pelagicore, is that meta-bistro contains general software recipes and configurations, aimed at the IVI domain, but no distribution and no images, whereas meta-pelux builds on top of meta-bistro by adding a distro and recipes to build complete system images.`

Yeah, I've thought about the same. Just want it to go through the code review and then move them to `meta-bistro`.

**Comment by erikboto** [comment]
> > Shouldn't recipes like this live in meta-bistro? According to the old thoughts, and the README of meta-pelux, this is the main idea behind meta-pelux and meta-bistro:
> > `The relationship with meta-bistro, which is also developed at Pelagicore, is that meta-bistro contains general software recipes and configurations, aimed at the IVI domain, but no distribution and no images, whereas meta-pelux builds on top of meta-bistro by adding a distro and recipes to build complete system images.`
> 
> Yeah, I've thought about the same. Just want it to go through the code review and then move them to `meta-bistro`.

Nice! I just had a quick look and it seems a few more recipes that should be in meta-bistro has sneaked in to meta-pelux, like mopidy and python-tornado.

**Comment by sashko** [comment]
This will go to `meta-bistro` instead.

**Pull request closed without merging**
