### PR TITLE
variant/local.conf.sample: Include bz2 type

### PR DESCRIPTION
**Pull request by fhajredini**
Signed-off-by: Fisnik Hajredini <fhajredini@luxoft.com>

### CODE REVIEW

**Comment by sashko** [comment]
what for?

**Comment by fhajredini** [comment]
> what for?

Updated the commit message

**Comment by sashko** [comment]
it will be a compressed image (~1GB) and it will be faster to download
    it supports compressed images for faster flashing to disk.
waot, what? so will we get, two images: wic and wic.bz2? how can one flash bz2 one without decompressing it?

**Comment by martin-ejdestig** [comment]
> how can one flash bz2 one without decompressing it?

bmaptool takes care of decompressing it: https://github.com/intel/bmap-tools/blob/master/docs/README#L236

(Presumably, I have not tried it myself yet. :)

**Comment by sashko** [comment]
> > how can one flash bz2 one without decompressing it?
> 
> bmaptool takes care of decompressing it: https://github.com/intel/bmap-tools/blob/master/docs/README#L236
> 
> (Presumably, I have not tried it myself yet. :)

okay, great. @fhajredini can you confirm? also, double check whether we need `wic.bmap` after this change or `wic.bmap.bz2` would be enough. don't forget about updating docs as well.

**Comment by fhajredini** [comment]
> > > how can one flash bz2 one without decompressing it?
> > 
> > 
> > bmaptool takes care of decompressing it: https://github.com/intel/bmap-tools/blob/master/docs/README#L236
> > (Presumably, I have not tried it myself yet. :)
> 
> okay, great. @fhajredini can you confirm? also, double check whether we need `wic.bmap` after this change or `wic.bmap.bz2` would be enough. don't forget about updating docs as well.

We still need wic.bmap

**Comment by sashko** [comment]
local.conf.sample: add wic.bmap.bz2 to IMAGE_FSTYPES / generate wic.bmap.bz2 IMAGE_FSTYPE for Intel and ARP

**Comment by fhajredini** [comment]
Just checked again, it can be flashed without bmap file too, but that wouldnt be so smart as it increases the time of the flashing a lot. I think that its the bmap file which takes use of the sparse bytes..

**Comment by sashko** [comment]
> Just checked again, it can be flashed without bmap file too, but that wouldnt be so smart as it increases the time of the flashing a lot. I think that its the bmap file which takes use of the sparse bytes..

I am not sure I understood you: isn't wic.bmap.bz just a compressed version of wic.bmap?

**Comment by fhajredini** [comment]
> > Just checked again, it can be flashed without bmap file too, but that wouldnt be so smart as it increases the time of the flashing a lot. I think that its the bmap file which takes use of the sparse bytes..
> 
> I am not sure I understood you: isn't wic.bmap.bz just a compressed version of wic.bmap?

No, wic.bmap is a file of 8KB. As far as i understand, its just a file which maps the image for easier flashing.. now the actual image is still required, and that can be a raw image(.wic) or a compressed image(.wic.bz2). Bmaptools can flash a compressed image on the fly. It can compress it with, or without the bmap file, but without it, it will take a longer time.

**Comment by sashko** [comment]
title is still ambiguous

**Comment by fhajredini** [comment]
bmap has already been included on the previous commits. This is just having a compressed image as an artifact.

**Pull request merged**
