### PR TITLE
qtapplicationmanager: fix path to library

### PR DESCRIPTION
**Pull request by sashko**
Fixed path to the library and cleaned up syntax a bit.

Signed-off-by: Oleksandr Kravchuk <oleksandr.kravchuk@pelagicore.com>

### CODE REVIEW

**Comment by sashko** [comment]
@martin-ejdestig the path has changed on `Qt 5.11`. This change is needed to bump `Qt` to `5.11` on `sumo`.

**Comment by martin-ejdestig** [comment]
I would split this commit in two. One commit for the actual fix and one with the cleanups.

We are not hit by this now because we are not on 5.11 yet? Or we do not build qtapplicationmanager?

**Comment by sashko** [comment]
@mardy we're not hit by this since we're not using 5.11 yet (we're on 5.10 atm)

**Comment by martin-ejdestig** [comment]
So if we commit this it will be broken until we update?

**Comment by sashko** [comment]
@martin-ejdestig well, if you manually fetch latest meta-pelux then yes, but since manifest will not be updated, CI/CD builds will work.

**Comment by martin-ejdestig** [comment]
But your plan is to update immediately after, or? If not, are we OK with not being able to update meta-pelux until that is done?

**Comment by sashko** [comment]
@martin-ejdestig the plan is to bump `meta-boot2qt` and `meta-qt5` right after all the necessary fixes are delivered to `meta-pelux`.

**Pull request merged**
