### PR TITLE
qtapplicationmanager: minor fixes to comment text

### PR DESCRIPTION
**Pull request by mardy**

### CODE REVIEW

**Comment by GordanM** [comment]
Please use https://codereview.qt-project.org/#/. This repository doesn't rely on github PRs.

**Comment by mardy** [comment]
You sure? :-)

**Comment by GordanM** [comment]
Yes. It's a one way mirror.

**Comment by mardy** [comment]
How can it be? I've already committed to this repo already...

**Comment by GordanM** [comment]
Woops, I'm a dunce. Somehow I thought you were modifying the QtApplicationManager repository on github. Sorry about that. Carry on :)

**Pull request merged**
