### PR TITLE
linux-intel: replace CAN config with KERNEL_FEATURES

### PR DESCRIPTION
**Pull request by sashko**
Yocto has KERNEL_FEATURES that enables CAN in the kernel. Use it to
decrease maintanance work.

Signed-off-by: Oleksandr Kravchuk <oleksandr.kravchuk@pelagicore.com>

### CODE REVIEW

**Comment by sashko** [comment]
> CONFIG_CAN_LEDS

those options are there, except `CONFIG_CAN_LEDS`, which we can enable if it is needed :poodle:

**Comment by JEderonn** [comment]
> > CONFIG_CAN_LEDS
> 
> those options are there, except `CONFIG_CAN_LEDS`, which we can enable if it is needed 🐩

So perhaps we shall enable this in meta-pelux so we are compatible with what we have provided earlier?

Please confirm that these configs are set to y and not m:
CONFIG_CAN_CALC_BITTIMING=y
CONFIG_CAN_PEAK_PCIEC=y

**Comment by sashko** [comment]
Here is can config's content:

```
# platform and USB devices
CONFIG_CAN=m
CONFIG_CAN_VCAN=m
CONFIG_CAN_CALC_BITTIMING=y
CONFIG_CAN_SJA1000=m
CONFIG_CAN_SJA1000_PLATFORM=m
CONFIG_CAN_C_CAN=m
CONFIG_CAN_C_CAN_PLATFORM=m
CONFIG_CAN_CC770=m
CONFIG_CAN_CC770_PLATFORM=m
CONFIG_CAN_SOFTING=m
CONFIG_CAN_SLCAN=m
CONFIG_CAN_IFI_CANFD=m
CONFIG_CAN_M_CAN=m
CONFIG_CAN_EMS_USB=m
CONFIG_CAN_ESD_USB2=m
CONFIG_CAN_GS_USB=m
CONFIG_CAN_KVASER_USB=m
CONFIG_CAN_PEAK_USB=m
CONFIG_CAN_8DEV_USB=m
# x86 PCH
#CONFIG_PCH_CAN=m
# drivers for ISA/PCI cards
CONFIG_CAN_C_CAN_PCI=m
# Philips/NXP SJA1000 based PCI(e)
CONFIG_CAN_EMS_PCI=m
CONFIG_CAN_PEAK_PCI=m
CONFIG_CAN_PEAK_PCIEC=m
CONFIG_CAN_KVASER_PCI=m
CONFIG_CAN_PLX_PCI=m
# SPI bus devices
CONFIG_CAN_MCP251X=m

```

**Comment by sashko** [comment]
@JEderonn CONFIG_CAN_LEDS is apparently not there because it is deprecated:
* https://lkml.org/lkml/2019/6/24/242
* https://lore.kernel.org/patchwork/patch/1050531/

**Pull request merged**
