### PR TITLE
Sumo

### PR DESCRIPTION
**Pull request by sashko**

### CODE REVIEW

**Comment by Gagi2k** [comment]
In general i'm fine to have this in the sumo branch, but shouldn't you just merge or rebase the sumo branch on top of master instead ? (where the picked commits are already in ?)

**Comment by sashko** [comment]
@Gagi2k yeah, that's probably better to do now

**Comment by sashko** [comment]
@tsansari it is just a rebase on master.

**Comment by sashko** [comment]
@fhajredini done

**Pull request merged**
