### PR TITLE
gammaray: add bbappend with temp rpath fix

### PR DESCRIPTION
**Pull request by sashko**
Signed-off-by: Oleksandr Kravchuk <oleksandr.kravchuk@pelagicore.com>

### CODE REVIEW

**Comment by sashko** [comment]
to clarify the change: rpath issue exists on the latest version of `gammaray`; `meta-boot2qt` will have to be bumped to use `Qt 5.11` on `sumo`.

**Comment by kanavin** [comment]
The error is most likely a package_qa failure, which has a check specifically for this:
https://git.yoctoproject.org/cgit/cgit.cgi/poky/tree/meta/classes/insane.bbclass#n98

I have to agree: there is an issue in the way the component is built, and fixing it after the fact at installation time is not right.

**Comment by sashko** [comment]
@kanavin I understand that bbappends with those kinds of fixes should be temporary solutions until the proper solution is mainstreamed, but I don't always have time (or just not in a mood) to fix it in the mainstream.

Can you suggest us a better way of working around those kinds of issues? Thanks.

**Comment by kanavin** [comment]
It's fine as a workaround if you don't have time, as long as it contains a link to the upstream ticket to fix this properly :)

**Pull request merged**
