### PR TITLE
Revert "qtbase: fix intermittent rpi-qtauto gammaray build failures" 

### PR DESCRIPTION
**Pull request by sashko**
The change has been upstreamed to meta-qt5.

The fix has been upstreamed to meta-qt5 (see @4ed43856587539ff18f2ff0).

Relevant discussion: https://github.com/meta-qt5/meta-qt5/issues/108

This reverts commit dce88dd84a2efc38a60d48a48e6a22752591b8ff.

### CODE REVIEW

**Comment by martin-ejdestig** [comment]
The review you are linking to and the commit are not related.

**Comment by sashko** [comment]
> The review you are linking to and the commit are not related.

Yes, sorry. Completely messed up changes.

**Comment by martin-ejdestig** [comment]
> The change has been upstreamed to meta-qt5.

Not true.

**Comment by sashko** [comment]
@martin-ejdestig https://github.com/meta-qt5/meta-qt5/blob/87f04621f3ceba43a2409b243cfe68f3dcaa4eff/recipes-qt/qt5/qtbase/0015-Qt5GuiConfigExtras.cmake.in-cope-with-variable-path-.patch

**Comment by martin-ejdestig** [comment]
Please provide some form of link in commit message itself. E.g. what you pasted in comment here or just say "see <hash> in meta-qt5".

**Comment by sashko** [comment]
> Please provide some form of link in commit message itself. E.g. what you pasted in comment here or just say "see in meta-qt5".

It doesn't: it's a patch for `qtbase` in `meta-qt5`.

**Comment by martin-ejdestig** [comment]
Hum... I do not understand what you mean. It is fixed in meta-qt5... refer to the fix somehow in the revert commit message.

**Comment by sashko** [comment]
> Hum... I do not understand what you mean. It is fixed in meta-qt5... refer to the fix somehow in the revert commit message.

Done. Ping.

**Comment by martin-ejdestig** [comment]
Wrong hash. It should be 4ed43856587539ff18f2ff08de296541087e1e31 . meta-qt5/meta-qt5@4ed43856587539ff18f2ff08de296541087e1e31 .

**Comment by martin-ejdestig** [comment]
The hash is still wrong... 8f2ff08de296541087e1e31 does not even exists in meta-qt5 as far as I can tell.

**Comment by sashko** [comment]
> The hash is still wrong... 8f2ff08de296541087e1e31 does not even exists in meta-qt5 as far as I can tell.

https://github.com/meta-qt5/meta-qt5/commit/4ed43856587539ff18f2ff08de296541087e1e31

**Comment by martin-ejdestig** [comment]
Yes, that is what I wrote in my comment. You still have 8f2ff08de296541087e1e31 in the commit message though, which does not exist in meta-qt5.

**Comment by sashko** [comment]
> Yes, that is what I wrote in my comment. You still have 8f2ff08de296541087e1e31 in the commit message though, which does not exist in meta-qt5.

I have just pointed you out to that commit.

**Comment by martin-ejdestig** [comment]
Can you please try to be a bit more clear.

As far as I can tell, the commit hash you have in your commit message, 8f2ff08de296541087e1e31, does not exists in meta-qt5. https://github.com/meta-qt5/meta-qt5/commit/8f2ff08de296541087e1e31 is a 404 and I have fetched meta-qt5 from git://code.qt.io/yocto/meta-qt5 as well and can not find it.

The commit link you have in the GitHub comment is the same on as I had, hash 4ed43856587539ff18f2ff08de296541087e1e31 and it does not 404: https://github.com/meta-qt5/meta-qt5/commit/4ed43856587539ff18f2ff08de296541087e1e31

So either I am missing something or the commit in the commit message is wrong.

**Pull request merged**
