### PR TITLE
swupdate: add comment regarding SRC_URI usage

### PR DESCRIPTION
**Pull request by TSAnsari**
Signed-off-by: Tariq Ansari <tansari@luxoft.com>

### CODE REVIEW

**Comment by sashko** [comment]
it doesn't really do anything except unifying the style, right? could you change the title, please? the current one doesn't really make much sense.

**Comment by TSAnsari** [comment]
Yes it just simplify/unify the code. Updated the commit message.

**Comment by FlorentRevest** [comment]
I don't _fully_ agree with this PR because sw-description is a "hard requirement" (swupdate won't work without it, no matter what the platform is) whereas emmcsetup.lua could be kept out of the update artifacts for certain targets (for instance, if the disk is already partitioned or if we don't use an A+B partitioning scheme).

That being said, I don't really mind either... If you think it makes sense to have everything in one SRC_URI even if we loose some semantic with that, I'm fine with merging this PR.

**Comment by TSAnsari** [comment]
@FlorentRevest Now that you explained why it was done like that before, it makes sense and I agree with your comments. So I want to keep it as it was. Only that the reason was not very obvious to me, so instead I will add a comment that explains the intention for someone thinking about it in the future.

**Comment by TSAnsari** [comment]
closing this as consensus is that the code is self explanatory

**Pull request closed without merging**
