### PR TITLE
Add openssh server to qtauto image

### PR DESCRIPTION
**Pull request by TSAnsari**
Signed-off-by: Tariq Ansari <tansari@luxoft.com>

### CODE REVIEW

**Comment by sashko** [comment]
Could you please explain why this doesn't work?

**Comment by Gagi2k** [comment]
Is there any reason why we just change the qtauto recipes ? Shouldn't the ssh-server be included already in the base image ?

**Comment by TSAnsari** [comment]
@Gagi2k I don't see it added in base image. It was only added to the following dev images
core-image-pelux-qtauto-neptune-dev.bb
core-image-pelux-minimal-dev.bb

**Comment by TSAnsari** [comment]
Based on the above discussion, that only dev image should contain ssh server,I am discarding this pull request

**Comment by Gagi2k** [comment]
@TSAnsari sorry you missunderstood me, i meant why we are not adding it also to the base image... But i guess @FlorentRevest already answered that before...

**Pull request closed without merging**
